// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.29.3
// source: proto/marketdata.proto

package md

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarketId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exchange string `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol   string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (x *MarketId) Reset() {
	*x = MarketId{}
	mi := &file_proto_marketdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketId) ProtoMessage() {}

func (x *MarketId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_marketdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketId.ProtoReflect.Descriptor instead.
func (*MarketId) Descriptor() ([]byte, []int) {
	return file_proto_marketdata_proto_rawDescGZIP(), []int{0}
}

func (x *MarketId) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *MarketId) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type Level struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price float64 `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Qty   float64 `protobuf:"fixed64,2,opt,name=qty,proto3" json:"qty,omitempty"`
}

func (x *Level) Reset() {
	*x = Level{}
	mi := &file_proto_marketdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Level) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Level) ProtoMessage() {}

func (x *Level) ProtoReflect() protoreflect.Message {
	mi := &file_proto_marketdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Level.ProtoReflect.Descriptor instead.
func (*Level) Descriptor() ([]byte, []int) {
	return file_proto_marketdata_proto_rawDescGZIP(), []int{1}
}

func (x *Level) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Level) GetQty() float64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

type OrderBookDelta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Market     *MarketId `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Sequence   uint64    `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	TsNs       uint64    `protobuf:"varint,3,opt,name=ts_ns,json=tsNs,proto3" json:"ts_ns,omitempty"`
	Bids       []*Level  `protobuf:"bytes,4,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks       []*Level  `protobuf:"bytes,5,rep,name=asks,proto3" json:"asks,omitempty"`
	IsSnapshot bool      `protobuf:"varint,6,opt,name=is_snapshot,json=isSnapshot,proto3" json:"is_snapshot,omitempty"`
}

func (x *OrderBookDelta) Reset() {
	*x = OrderBookDelta{}
	mi := &file_proto_marketdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookDelta) ProtoMessage() {}

func (x *OrderBookDelta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_marketdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookDelta.ProtoReflect.Descriptor instead.
func (*OrderBookDelta) Descriptor() ([]byte, []int) {
	return file_proto_marketdata_proto_rawDescGZIP(), []int{2}
}

func (x *OrderBookDelta) GetMarket() *MarketId {
	if x != nil {
		return x.Market
	}
	return nil
}

func (x *OrderBookDelta) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *OrderBookDelta) GetTsNs() uint64 {
	if x != nil {
		return x.TsNs
	}
	return 0
}

func (x *OrderBookDelta) GetBids() []*Level {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *OrderBookDelta) GetAsks() []*Level {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *OrderBookDelta) GetIsSnapshot() bool {
	if x != nil {
		return x.IsSnapshot
	}
	return false
}

type StreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Markets []*MarketId `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_proto_marketdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_marketdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_marketdata_proto_rawDescGZIP(), []int{3}
}

func (x *StreamRequest) GetMarkets() []*MarketId {
	if x != nil {
		return x.Markets
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_marketdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_marketdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_marketdata_proto_rawDescGZIP(), []int{4}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_marketdata_proto protoreflect.FileDescriptor

var file_proto_marketdata_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x6d, 0x64, 0x22, 0x3e, 0x0a, 0x08,
	0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0x2f, 0x0a, 0x05,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x71,
	0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x71, 0x74, 0x79, 0x22, 0xc6, 0x01,
	0x0a, 0x0e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x44, 0x65, 0x6c, 0x74, 0x61,
	0x12, 0x24, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x6d, 0x64, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x52, 0x06,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x73, 0x5f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x04, 0x74, 0x73, 0x4e, 0x73, 0x12, 0x1d, 0x0a, 0x04, 0x62, 0x69, 0x64, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6d, 0x64, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x52, 0x04, 0x62, 0x69, 0x64, 0x73, 0x12, 0x1d, 0x0a, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6d, 0x64, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52,
	0x04, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x73, 0x6e, 0x61, 0x70,
	0x73, 0x68, 0x6f, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x22, 0x37, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x07, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x64, 0x2e, 0x4d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x52, 0x07, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x22,
	0x15, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x32, 0x49, 0x0a, 0x0d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42,
	0x6f, 0x6f, 0x6b, 0x46, 0x65, 0x65, 0x64, 0x12, 0x38, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x11, 0x2e, 0x6d, 0x64, 0x2e, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6d, 0x64, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x28, 0x01, 0x30,
	0x01, 0x32, 0x3f, 0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2b, 0x0a, 0x0a, 0x50, 0x75, 0x73, 0x68, 0x44, 0x65, 0x6c,
	0x74, 0x61, 0x73, 0x12, 0x12, 0x2e, 0x6d, 0x64, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f,
	0x6f, 0x6b, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x1a, 0x07, 0x2e, 0x6d, 0x64, 0x2e, 0x41, 0x63, 0x6b,
	0x28, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x64, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_marketdata_proto_rawDescOnce sync.Once
	file_proto_marketdata_proto_rawDescData = file_proto_marketdata_proto_rawDesc
)

func file_proto_marketdata_proto_rawDescGZIP() []byte {
	file_proto_marketdata_proto_rawDescOnce.Do(func() {
		file_proto_marketdata_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_marketdata_proto_rawDescData)
	})
	return file_proto_marketdata_proto_rawDescData
}

var file_proto_marketdata_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_marketdata_proto_goTypes = []any{
	(*MarketId)(nil),       // 0: md.MarketId
	(*Level)(nil),          // 1: md.Level
	(*OrderBookDelta)(nil), // 2: md.OrderBookDelta
	(*StreamRequest)(nil),  // 3: md.StreamRequest
	(*Ack)(nil),            // 4: md.Ack
}
var file_proto_marketdata_proto_depIdxs = []int32{
	0, // 0: md.OrderBookDelta.market:type_name -> md.MarketId
	1, // 1: md.OrderBookDelta.bids:type_name -> md.Level
	1, // 2: md.OrderBookDelta.asks:type_name -> md.Level
	0, // 3: md.StreamRequest.markets:type_name -> md.MarketId
	3, // 4: md.OrderBookFeed.StreamBooks:input_type -> md.StreamRequest
	2, // 5: md.OrderBookIngress.PushDeltas:input_type -> md.OrderBookDelta
	2, // 6: md.OrderBookFeed.StreamBooks:output_type -> md.OrderBookDelta
	4, // 7: md.OrderBookIngress.PushDeltas:output_type -> md.Ack
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_marketdata_proto_init() }
func file_proto_marketdata_proto_init() {
	if File_proto_marketdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_marketdata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_marketdata_proto_goTypes,
		DependencyIndexes: file_proto_marketdata_proto_depIdxs,
		MessageInfos:      file_proto_marketdata_proto_msgTypes,
	}.Build()
	File_proto_marketdata_proto = out.File
	file_proto_marketdata_proto_rawDesc = nil
	file_proto_marketdata_proto_goTypes = nil
	file_proto_marketdata_proto_depIdxs = nil
}
