# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import marketdata_pb2 as marketdata__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in marketdata_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderBookFeedStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamBooks = channel.stream_stream(
                '/md.OrderBookFeed/StreamBooks',
                request_serializer=marketdata__pb2.StreamRequest.SerializeToString,
                response_deserializer=marketdata__pb2.OrderBookDelta.FromString,
                _registered_method=True)


class OrderBookFeedServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamBooks(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderBookFeedServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamBooks': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamBooks,
                    request_deserializer=marketdata__pb2.StreamRequest.FromString,
                    response_serializer=marketdata__pb2.OrderBookDelta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'md.OrderBookFeed', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('md.OrderBookFeed', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderBookFeed(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamBooks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/md.OrderBookFeed/StreamBooks',
            marketdata__pb2.StreamRequest.SerializeToString,
            marketdata__pb2.OrderBookDelta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OrderBookIngressStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushDeltas = channel.stream_unary(
                '/md.OrderBookIngress/PushDeltas',
                request_serializer=marketdata__pb2.OrderBookDelta.SerializeToString,
                response_deserializer=marketdata__pb2.Ack.FromString,
                _registered_method=True)


class OrderBookIngressServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PushDeltas(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderBookIngressServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushDeltas': grpc.stream_unary_rpc_method_handler(
                    servicer.PushDeltas,
                    request_deserializer=marketdata__pb2.OrderBookDelta.FromString,
                    response_serializer=marketdata__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'md.OrderBookIngress', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('md.OrderBookIngress', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderBookIngress(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushDeltas(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/md.OrderBookIngress/PushDeltas',
            marketdata__pb2.OrderBookDelta.SerializeToString,
            marketdata__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
