# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: marketdata.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'marketdata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10marketdata.proto\x12\x02md\",\n\x08MarketId\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\"#\n\x05Level\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x0b\n\x03qty\x18\x02 \x01(\x01\"\x96\x01\n\x0eOrderBookDelta\x12\x1c\n\x06market\x18\x01 \x01(\x0b\x32\x0c.md.MarketId\x12\x10\n\x08sequence\x18\x02 \x01(\x04\x12\r\n\x05ts_ns\x18\x03 \x01(\x04\x12\x17\n\x04\x62ids\x18\x04 \x03(\x0b\x32\t.md.Level\x12\x17\n\x04\x61sks\x18\x05 \x03(\x0b\x32\t.md.Level\x12\x13\n\x0bis_snapshot\x18\x06 \x01(\x08\".\n\rStreamRequest\x12\x1d\n\x07markets\x18\x01 \x03(\x0b\x32\x0c.md.MarketId\"\x11\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x32I\n\rOrderBookFeed\x12\x38\n\x0bStreamBooks\x12\x11.md.StreamRequest\x1a\x12.md.OrderBookDelta(\x01\x30\x01\x32?\n\x10OrderBookIngress\x12+\n\nPushDeltas\x12\x12.md.OrderBookDelta\x1a\x07.md.Ack(\x01\x42\nZ\x08proto/mdb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'marketdata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010proto/md'
  _globals['_MARKETID']._serialized_start=24
  _globals['_MARKETID']._serialized_end=68
  _globals['_LEVEL']._serialized_start=70
  _globals['_LEVEL']._serialized_end=105
  _globals['_ORDERBOOKDELTA']._serialized_start=108
  _globals['_ORDERBOOKDELTA']._serialized_end=258
  _globals['_STREAMREQUEST']._serialized_start=260
  _globals['_STREAMREQUEST']._serialized_end=306
  _globals['_ACK']._serialized_start=308
  _globals['_ACK']._serialized_end=325
  _globals['_ORDERBOOKFEED']._serialized_start=327
  _globals['_ORDERBOOKFEED']._serialized_end=400
  _globals['_ORDERBOOKINGRESS']._serialized_start=402
  _globals['_ORDERBOOKINGRESS']._serialized_end=465
# @@protoc_insertion_point(module_scope)
