# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: executor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xecutor.proto\x12\x04\x65xec\"M\n\x0bTriangleLeg\x12\x0e\n\x06market\x18\x01 \x01(\t\x12\x0c\n\x04side\x18\x02 \x01(\t\x12\x0b\n\x03qty\x18\x03 \x01(\x01\x12\x13\n\x0blimit_price\x18\x04 \x01(\x01\"\xa7\x01\n\x04Plan\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\x1f\n\x04legs\x18\x02 \x03(\x0b\x32\x11.exec.TriangleLeg\x12\x1d\n\x15\x65xpected_profit_quote\x18\x03 \x01(\x01\x12\x11\n\tquote_ccy\x18\x04 \x01(\t\x12\x10\n\x08valid_ms\x18\x05 \x01(\x04\x12\x17\n\x0fmax_slippage_bp\x18\x06 \x01(\x01\x12\x0f\n\x07plan_id\x18\x07 \x01(\t\"0\n\x0cProposeReply\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t29\n\x08\x45xecutor\x12-\n\x0bProposePlan\x12\n.exec.Plan\x1a\x12.exec.ProposeReplyB\x0cZ\nproto/execb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\nproto/exec'
  _globals['_TRIANGLELEG']._serialized_start=24
  _globals['_TRIANGLELEG']._serialized_end=101
  _globals['_PLAN']._serialized_start=104
  _globals['_PLAN']._serialized_end=271
  _globals['_PROPOSEREPLY']._serialized_start=273
  _globals['_PROPOSEREPLY']._serialized_end=321
  _globals['_EXECUTOR']._serialized_start=323
  _globals['_EXECUTOR']._serialized_end=380
# @@protoc_insertion_point(module_scope)
